import type { ITheme, IStyle } from '@fluentui/react';

export interface IRulesManagerProps {
  theme?: ITheme;
}

export interface IRulesManagerStyleProps {
  theme?: ITheme;
}

export interface IRulesManagerStyles {
  container: IStyle;
  header: IStyle;
  title: IStyle;
  rulesList: IStyle;
  ruleItem: IStyle;
  ruleItemEditing: IStyle;
  ruleItemAdding: IStyle;
  ruleContent: IStyle;
  ruleLeftSection: IStyle;
  ruleName: IStyle;
  ruleNameField: IStyle;
  toggleContainer: IStyle;
  actionButtons: IStyle;
  autoGeneratedLabel: IStyle;
  noRules: IStyle;
  pagination: IStyle;
  paginationInfo: IStyle;
  messageBar: IStyle;
}
