import { classNamesFunction } from '@fluentui/react';
import { IRulesManagerStyleProps, IRulesManagerStyles } from './RulesManager.types';

export const getStyles = (props: IRulesManagerStyleProps): IRulesManagerStyles => {
  const { theme } = props;

  return {
    container: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    title: {
      fontSize: '16px',
      fontWeight: 600,
      color: theme?.palette.neutralPrimary,
    },
    rulesList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
    },
    ruleItem: {
      border: `1px solid ${theme?.palette.neutralTertiary || '#999999'}`,
      borderRadius: '4px',
      padding: '8px 12px',
      background: theme?.palette.neutralLight || '#f8f9fa',
      minHeight: '32px',
      display: 'flex',
      alignItems: 'center',
    },
    ruleItemEditing: {
      border: `2px solid ${theme?.palette.themePrimary || '#6264a7'}`,
      background: theme?.palette.neutralLighter || '#ececf1',
    },
    ruleItemAdding: {
      border: `2px solid ${theme?.palette.themePrimary || '#6264a7'}`,
      background: theme?.palette.neutralLighter || '#ececf1',
      padding: '12px',
    },
    ruleContent: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
    },
    ruleLeftSection: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      flex: 1,
    },
    ruleName: {
      flex: 1,
      fontSize: '14px',
      color: theme?.palette.neutralPrimary,
    },
    ruleNameField: {
      flex: 1,
      '& .ms-TextField': {
        minHeight: '28px',
      },
      '& .ms-TextField-field': {
        fontSize: '14px',
        padding: '2px 6px',
        resize: 'none',
      },
    },
    toggleContainer: {
      minWidth: '50px',
      '& .ms-Toggle': {
        margin: 0,
      },
      '& .ms-Toggle-label': {
        display: 'none',
      },
      '& .ms-Toggle-innerContainer': {
        margin: 0,
      },
    },
    actionButtons: {
      display: 'flex',
      gap: '4px',
      marginLeft: '8px',
    },
    autoGeneratedLabel: {
      fontSize: '12px',
      color: theme?.palette.neutralSecondary || '#666666',
      fontStyle: 'italic',
      padding: '4px 8px',
      backgroundColor: theme?.palette.neutralLighter || '#f8f9fa',
      border: `1px solid ${theme?.palette.neutralTertiary || '#999999'}`,
      borderRadius: '4px',
    },
    noRules: {
      color: theme?.palette.neutralSecondary || '#666666',
      textAlign: 'center',
      padding: '20px',
      fontSize: '14px',
    },
    pagination: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      marginTop: '16px',
    },
    paginationInfo: {
      fontSize: '14px',
      color: theme?.palette.neutralSecondary,
      margin: '0 16px',
    },
    messageBar: {
      marginBottom: '8px',
    },
  };
};

export const getClassNames = classNamesFunction<IRulesManagerStyleProps, IRulesManagerStyles>();
